### ISSUE TITLE
Suggestion: split `hca.ts` into multiple source files

### ISSUE THREAD

**Issue by reosablo** [y2361547758/hca.js#8]
# Motivation

The current [`hca.ts`](https://github.com/y2361547758/hca.js/blob/f0bdd811bc2ea35c7df43fe484cf3bf99621c898/hca.ts) is about 3,000 lines and it's hard to maintain or understand.
I made a branch to split this large code into multiple files to improve development experience.

https://github.com/reosablo/hca.js/tree/feature/split-source

@y2361547758 @segfault-bilibili 
If you like it, I'll send PR. [(diff)](https://github.com/y2361547758/hca.js/compare/master...reosablo:feature/split-source)

# About the suggested branch

### before
```
(root)
|_ hca.ts ... all-in-one source code
|_ hca.js ... generated code
```

### after
```
(root)
|_ src/
  |_ VGAudio/        ... codes ported from VGAudio
  |_ wav/            ... codes for wav data
  |_ worker/         ... codes for WebWorker
  |_ index.ts        ... The original hca.ts becomes this
|_ hca.d.ts          ... generated code (TypeScript type information for hca.js)
|_ hca.js            ... generated code
|_ package-lock.json ... generated by `npm install` to remember dependency package versions.
|_ package.json      ... dependency package information for npm
|_ rollup.config.js  ... configuration for rollup
```

- `hca.js` is built from [`src/index.ts`](https://github.com/reosablo/hca.js/blob/feature/split-source/src/index.ts).
- files under the [`src/VGAudio`](https://github.com/reosablo/hca.js/tree/feature/split-source/src/VGAudio) directory is similar to [the original VGAudio source files](https://github.com/Thealexbarney/VGAudio/tree/master/src/VGAudio)

### npm

npm is a standard package manager for Node.js.
If you have already installed Node.js, `npm` command should be ready to use.
This is an well-known tool for JavaScript / TypeScript developers.

### rollup

[rollup][rollup] is a JavaScript bundler to build codes from multiple source files.
This is also an well-known tool. (8M downloads per week)
You can install this by following build step.

## How to build

1. Clone the repository
2. Change you current directory into the local repository
3. Run `npm install` [^1] to install dependency packages
4. Run `npm run build` [^2] to generate `hca.js` and `hca.d.ts` [^3]
5. Run `npm run generate-standalone` to generate `hca-standalone.html`

[rollup]: https://rollupjs.org/
[^1]: No command line options are required. `npm install` is command to install dependency packages specified in `package.json`. [`rollup`](https://www.npmjs.com/package/rollup), [`rollup-plugin-ts`](https://www.npmjs.com/package/rollup-plugin-ts) and their dependency packages are downloaded into `node_modules` directory.
[^2]: `npm run` is a command to run scripts specified in `package.json`. `npm run build` will execute `rollup -c` in this case. `rollup` command is not available unless you don't run `npm install`
[^3]: `.d.ts` is a TypeScript type information file for library users to enable intellisense or static type check.

**Comment by y2361547758** [comment]
I learned JS myself before [2016](https://hackernoon.com/how-it-feels-to-learn-javascript-in-2016-d3a717dd577f) without systematically. And this project was designed with only one function, and since we can use `await` in Chrome, I even don't want any compilation step, so I write this as one file lib. And I only want this run on Chrome (Win and Android).

Then to implement some addition features, we need more modern Web/JS ability, this project is getting bigger. It's better to refactor all code in some modern JS project way, and **all compile or generate things should drop in release page or a GitHub Pages branch**. Maybe deploy as FaaS (like CloudFlare workers) is a nother way.

I do know `Webpack` and `Babel` but not familiar with `rollup`, in fact I'm not work on fontend for years (some Rust and WASM for now). According to my understanding, this project may not the best practice, there should be a way to convert HCA to OPUS or some other encoding without iMDCT so that we can finish convertion in `O(n)` and do any other thing in common way. I'd like to study the working principle of HCA deeper but, well, busy with works.

I'm glad you and anyone can maintain this project, PR is welcome.

**Comment by reosablo** [comment]
@y2361547758 
That sounds great! I hope you'll achieve it.

> I'm glad you and anyone can maintain this project, PR is welcome.

Hmm... Maybe I can do that but the PR will be just for developers of this repository.
At this time, I won't send PR and keep my suggested branch. Thank you!
